### ISSUE TITLE
Đăng nhập tài khoản

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#35]
*Giao diện:
Trong trang đăng nhập hiển thị:
Input tên tài khoản 
Input mật khẩu
Button đăng nhập
Button hủy
*Dữ liệu:
Lưu trữ data gồm có các thông tin: tài khoản, mật khẩu, mã quyền, trạng thái
*Xử lý:
-  Nếu nhân viên chưa nhập tài khoản mật khẩu sẽ thông báo ràng buộc "Vui lòng nhập tài khoản " và  "Vui lòng nhập mật khẩu" 
- Nếu nhân viên nhập tài khoản nhưng chưa nhập mật khẩu thông báo"Vui lòng nhập mật khẩu"
- Nếu nhân viên nhập mật khẩu nhưng chưa nhập tài khoản thông báo "Vui lòng nhập tài khoản"
- Nếu nhân viên nhập đầy đủ nhưng khác quyền thông báo "không có quyền truy cập"
- Nếu nhân viên nhập đầy đủ và có quyền truy cập nhưng trạng thái tài khoản chưa kích hoạt thì thông báo "Tài khoản chưa kích hoạt"
- "Người dùng điền đầy đủ thông tin có quyền truy cập và kích hoạt trạng thái tài khoản => ấn nút đăng nhập => đăng nhập thành công
Khi ấn nút "hủy" sẽ clear các thông tin input

**Comment by datnv72** [comment]
Giao diện:
Trong trang đăng nhập hiển thị:
Input tên tài khoản 
Input mật khẩu
Button đăng nhập
Button hủy
*Xử lý:
TH1: Người dùng điền đầy đủ thông tin => ấn nút đăng nhập => đăng nhập thành công
TH2: Người dùng diền thiếu thông tin hoặc sai => ấn nút đăng nhập => báo ràng buộc, thông báo đăng nhập thất bại
Khi ấn nút "hủy" sẽ clear các thông 

*Dữ liệu:
Lưu trữ vào data gồm có các thông tin: tài khoản, mật khẩu

**Comment by Anllv** [comment]
da nhan
