### ISSUE TITLE
Thêm loại món ăn

### ISSUE THREAD

**Issue by thanhtai1812** [hunglp2k1/fast_food_app#36]
**Giao diện:** 
+ Input của thêm loại món ăn 
+ Button "Lưu" loại món ăn
+ Button "Trở lại" về trang danh sách món ăn
**Xử Lý:**
+ Trường Hợp 1: Khi không nhập vào trường input tên loại món ăn và ấn "Lưu" sẽ thông báo: Vui lòng điền đầy đủ thông tin loại món ăn
+ Trường hợp 2: Sau khi điền đầy đủ thông tin > ấn button "Lưu" thì sẽ lưu thông tin đó vào danh sách loại món ăn 
+ Chọn button "trở lại" sẽ trở lại trang danh sách loại món ăn
**Lưu trữ:**
+ MaLoaiMonAn, TenLoaiMonAn sẽ được lưu vào database

**Comment by datnv72** [comment]
Đã nhận

**Comment by datnv72** [comment]
đã xong
