### ISSUE TITLE
Sửa loại món ăn 

### ISSUE THREAD

**Issue by thanhtai1812** [hunglp2k1/fast_food_app#37]
**Giao diện:**
+ Input "Tên Loại Món Ăn"
+ Button "Lưu"
+ Button "Trở lại"
**Xử lý:**
+ Trường hợp 1: khi để trống thông tin cần sửa, chọn button "Lưu" sẽ hiển thị thông báo "Vui lòng nhập đầy đủ thông tin"
+ Trường hợp 2: Sau khi sửa thông tin cần sửa chọn nút "Lưu" sẽ lưu lại thông tin đã sửa
+ Khi ấn button "Trở lại" sẽ trở về trang danh sách loại món ăn
**Lưu trữ:**
+ Lưu trữ thông tin tên loại món ăn đã sửa vào database

**Comment by datnv72** [comment]
Đã nhận
