### ISSUE TITLE
Xóa loại món ăn 

### ISSUE THREAD

**Issue by thanhtai1812** [hunglp2k1/fast_food_app#38]
**Giao diện:** 
+ Hiển thị thông tin của tên loại món ăn
+ Button "Xóa"
+ Button "Trở lại"
**Xử lý:**
Chọn button "Xóa", loại món ăn đó sẽ được xóa
Chọn "trở lại" để trở lại màn hình danh sách loại món ăn
**Lưu trữ:**
Những thông tin đã xóa thì sẽ bị xóa khỏi database

**Comment by datnv72** [comment]
Đã nhận
