### ISSUE TITLE
Xem màn hình chính

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#39]
*Giao diện: 
+ Top header có hiển thị tài khoản nhân viên và button đăng xuất
+ Middle header gồm logo bên trái , thanh navigation (thực đơn, thông tin cá nhân) ở giữa và Icon giỏ hàng bên phải
+ Dưới top header có màn hình chào gồm: background - image và tên nhân viên, thời gian hiện tại hiển thị bên trong background - image
+ Main: 
   - Top header có thanh navigation - menu để hiển thị các loại món ăn và loại combo
   - Bottom header có sắp xếp dạng dropdownlist nằm ở bên trái, có thẻ span hiển thị số lượng món ăn nằm ở giữa, input tìm kiếm món ăn nằm ở bên phải
   -  Body Main hiển thị danh sách món ăn theo dạng grid 4 columns
   - Cart item gồm: Hình ảnh món ăn, tên món ăn, giá tiền,
 + Footer hiển thị bản quyền HuflitFood 
*Xử lý:
      - Khi đăng nhập thành công sẽ tạo Session cho tài khoản đã login thành công.
      - Nếu Session đó tồn tại thì sẽ vào trang chủ 
      - Nếu Session đó không tồn tại quay về trang đăng nhập
*Lưu Trữ:
    +Lưu các dữ liệu từ database gồm: Session của user name

**Comment by hunglp2k1** [comment]
Đã nhận!

**Comment by hunglp2k1** [comment]
Đã commit và push lên branch "hung"
