### ISSUE TITLE
Tìm kiếm món ăn 

### ISSUE THREAD

**Issue by thanhtai1812** [hunglp2k1/fast_food_app#40]
**Giao diện:**
+ Dropdownlist "loại món ăn"
+ Thanh tìm kiếm món ăn
+ icon button tìm kiếm
**Xử lý:**
- Tìm kiếm theo loại món ăn:
+ Dropdownlist: Chọn dropdownlist - loại món ăn ấn sẽ hiển thị danh sách các loại món ăn, ấn chọn loại món ăn tiếp đến ấn icon button sẽ hiển thị danh sách các món ăn có liên quan đến loại món ăn đó
- Tìm kiếm theo tên món ăn:
+Trường hợp 1: Nhập thông tin tìm kiếm chọn icon button "tìm kiếm" sẽ hiển thị các món ăn có liên quan
+Trường hợp 2: Nhập thông tin tìm kiếm chọn icon button tìm kiếm" sẽ thông báo không có món ăn
- Tìm kiếm theo tên và loại món ăn:
+Trường hợp 1: Chọn loại món ăn và điền tên món ăn ấn icon button sẽ hiển thị ra món ăn trong loại món ăn đã chọn
+Trường hợp 2: Chọn loại món ăn và điền tên món ăn ấn icon button sẽ thông báo không có món ăn trong loại món ăn đó.

**Comment by Anllv** [comment]
Đã nhận và đang thực hiện
