### ISSUE TITLE
Thêm món ăn 

### ISSUE THREAD

**Issue by thanhtai1812** [hunglp2k1/fast_food_app#41]
**Giao diện:**
+ Input "tên món ăn"
+ Input "mô tả"
+ Input image "hình ảnh món ăn"
+ Dropdownlist "loai món ăn"
+ Input "giá"
+ Input "Số lượng"
+ Button "Thêm mới"
+ Button "Trở lại"
**Xử lý:**
+Trường hợp 1: Điền đầy đủ các thông tin yêu cầu chọn button "thêm mới", món ăn sẽ được thêm vào danh sách món ăn
+ Trường hợp 2: Điền không đầy đủ các thông tin yêu cầu chọn button "thêm mới" sẽ hiển thị thông báo "Vui lòng điền đầy đủ các thông tin"
+ Ấn button "trở lại" quay trở lại trang danh sách món ăn
**Lưu trữ:**
+ Sau khi thực hiện thêm mới thông tin món ăn, các thông tin đó sẽ được lưu trữ vào database

**Comment by hunglp2k1** [comment]
đã nhận
