### ISSUE TITLE
Xem danh mục món ăn 

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#43]
*Giao diện: 
- Hiển thị thanh navigation - menu theo hàng ngang có text màu trắng, background màu xanh, border màu đen
- Khi người dùng hover vào mỗi navigation-item thì sẽ đổi sang text màu xanh, background màu trắng
*Xử lý: Sau khi đăng nhập thành công và sẽ vào trang chủ -> Sẽ lấy dữ liệu từ bảng loại món ăn hiển thị tên loại món ăn và loại combo ra màn hình trang chủ
*Dữ liệu: Lưu tên loại món ăn loại combo

**Comment by thanhtai1812** [comment]
Đã nhận
