### ISSUE TITLE
Xóa món ăn 

### ISSUE THREAD

**Issue by thanhtai1812** [hunglp2k1/fast_food_app#44]
**Giao diện:** 
+ Hiển thị thông tin của món ăn
+ Input "xóa"
+ Input "Trở lại"
**Xử lý:**
+ Chọn button "xóa" món ăn sẽ được xóa và quay trở lại trang danh sách món ăn
+ Ấn button "trở lại" để quay trở lại trang danh sách món ăn
 **Lưu trữ**
+Chọn "Xóa" sẽ  "Xóa" thành công -> dữ liệu các thông tin món ăn (MaMonAn, TenMonAn, Gia, Hinhanh, Soluong) sẽ được xóa khỏi database

**Comment by hunglp2k1** [comment]
đã nhận
