### ISSUE TITLE
Hiển thị danh sách món ăn theo loại món ăn

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#45]
*Giao diện :  
- Thanh navigation-menu hiển thị loại món ăn, loại combo 
- Dạng grid hiển thị danh sách loại món ăn
*Xử lý 
- Đăng nhập thành công 
- Session được tạo 
- Vào trang chủ 
- Click chọn navigation-item sẽ lấy các loại món ăn từ navigation đó và hiển thị ra danh sách món ăn của loại món ăn đó 
*Dữ liệu:
Dữ liệu gồm session, table loại món ăn, loại combo, table món ăn

**Comment by Anllv** [comment]
đã nhận và đang thực hiện
