### ISSUE TITLE
Xem giỏ hàng

### ISSUE THREAD

**Issue by hunglp2k1** [hunglp2k1/fast_food_app#47]
*Giao diện:
- icon cart ở trang chủ user
- Table hiển thị dữ liệu món ăn đã thêm vào giỏ hàng
- Row title hiển thị Tên món ăn, Hình ảnh món ăn ,số lượng món, thành tiền của mỗi món ăn
- Button "thêm món" để tiếp tục thêm món ăn ở dưới góc trái danh sách món ăn trong giỏ hàng.
- Dropdownlist  hiển thị các voucher giảm giá lấy từ table KhuyenMai, button "áp dụng khuyến mãi"
- Table hiển thị giá trước giảm, giá sau giảm, tổng tiền, nhân viên bán hàng, thời gian
- Button thanh toán
*Xử lí
- Đăng nhập thành công 
- Session được tạo
- Vào trang chủ
- Nếu lần đầu, chưa tạo order, chưa có món ăn trong giỏ hàng. Chọn icon cart ở trang chủ thì không nhảy vào xem giỏ hàng được.
- Ngược lại, đã tạo order, hệ thống tạo session cart -> Khi chọn icon cart ở trang chủ thì mới nhảy vào xem giỏ hàng được.
3. Dữ liệu
- Tên món ăn
- Hình ảnh món ăn
- Số lượng món ăn
- Thành tiền
- Tổng tiền
- Tỷ lệ giá giảm 
- Giá trước giảm
- Giá sau giảm

**Comment by thanhtai1812** [comment]
Đã nhận
