### ISSUE TITLE
Cập nhật số lượng món ăn trong giỏ hàng

### ISSUE THREAD

**Issue by hunglp2k1** [hunglp2k1/fast_food_app#48]
1. Giao diện
- Button (-) (+) giảm
2. Xử lí
- Khi chọn button (-) -> số lượng món ăn sẽ giảm -> chọn icon update để update lại số lượng món ăn -> Thành tiền sẽ giảm giá  theo -> Tổng tiền cũng giảm giá theo
- Khi chọn button (+) -> số lượng món ăn sẽ tăng-> chọn icon update để update lại số lượng món ăn -> Thành tiền sẽ tăng giá  theo -> Tổng tiền cũng tăng giá theo -> Thành tiền sẽ tăng theo
- Cập nhật lại session cart
3. Dữ liệu
- Số lượng món ăn(nvarchar(100))

**Comment by Anllv** [comment]
Đã nhận
