### ISSUE TITLE
Xóa món ăn khỏi giỏ hàng

### ISSUE THREAD

**Issue by hunglp2k1** [hunglp2k1/fast_food_app#49]
1. Giao diện
- Icon delete ở mỗi món ăn
2. Xử lí
- Session cart đã tạo
- Món ăn có trong giỏ hàng
- Chọn icon delete để xoá món ăn đó
- Session cart được cập nhật lại
3. Dữ liệu
- Tên món ăn
- Hình ảnh món ăn
- Số lượng
- Thành tiền

**Comment by datnv72** [comment]
đã nhận

**Comment by datnv72** [comment]
đã xong
