### ISSUE TITLE
Tiếp tục thêm món ăn vào giỏ hàng

### ISSUE THREAD

**Issue by hunglp2k1** [hunglp2k1/fast_food_app#50]
1. Giao diện
- Button thêm món ở dưới danh sách món ăn ở giỏ hàng
2. Xử lí
- Khi Session cart đã tạo
- Món ăn đã được thêm vào giỏ hàng
- Chọn button thêm món để tiếp tục thêm món ăn vào giỏ hàng
- Session cart vẫn duy trì
- Món ăn và số lượng món ăn vẫn còn được lưu trữ lại
3. Dữ liệu
- Tên món ăn
- Số lượng món
- Thành tiền
- Session món

**Comment by thanhtai1812** [comment]
Đã nhận
