### ISSUE TITLE
Thanh toán hoá đơn

### ISSUE THREAD

**Issue by hunglp2k1** [hunglp2k1/fast_food_app#51]
*Giao diện
- Table hiển thị: Tên nhân viên thanh toán, thời gian thanh toán, mã hoá đơn, số lượng món ăn, tên món ăn, giá trước giảm, giá khuyến mãi, giá sau giảm
*Xử lí:
- Khi đã có món ăn ở trang giỏ hàng
- Hiển thị thông tin: Nhân viên thanh toán, ngày giờ hiện tại, tiền trước giảm, tiền khuyến mãi, tiền sau khi giảm
- Chọn button thanh toán
- Dữ liệu sẽ được lưu vào database
*Dữ liệu
- Mã hoá đơn được tạo, thời gian thanh toán được lưu vào table HOADON
- Danh sách món  ăn, số lượng từng món ăn trong giỏ hàng, nhân viên thanh toán thì được lưu vào table CHITIETHOADON

**Comment by thanhtai1812** [comment]
Đã nhận
