### ISSUE TITLE
Thêm thông tin nhân viên

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#52]
"- Người quản lý có quyền tạo thông tin nhân viên.
1. Giao diện: 
Chọn vào nút ""thêm"" sau đó chuyển sang trang thêm nhân viên:
-> Gồm các input để nhập thông tin của nhân viên: 
 + Họ và tên
 + Giới tính
 + Sđt
 + Ngày sinh
2. Cơ sở dữ liệu:
Lưu trữ 
 + Họ và tên
 + Giới tính
 + Sđt
 + Ngày sinh 
+ Các thông tin được thêm mưới
3. Sau khi nhập đầy đủ thông tin chọn nút ""Lưu"" hoặc ""Hủy""
 TH1: Chọn ""Lưu"" sẽ xảy ra ràng buộc thông báo những field bắt buộc nhập nếu bỏ sót 
-> Nếu ""Lưu"" thành công -> dữ liệu các thông tin nhân viên(MaNV, HoVaTen, GioiTinh, Sđt) sẽ được lưu trong database
TH2: Chọn "Hủy"quay trở về  trang danh sách nhân viên

**Comment by datnv72** [comment]
đã nhận
