### ISSUE TITLE
Sửa thông tin nhân viên

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#53]
"- Người quản lý có quyền sửa  thông tin nhân viên hiện có.
1. Chọn vào nút ""thêm"" sau đó chuyển sang trang thêm nhân viên:
-> Gồm các input để nhập thông tin của nhân viên: 
 + HovaTen(not null, nVarchar(250),
 + GioiTinh(null, char(3)),
 + Sđt(null, char(11)) 
2. Sau khi nhập đầy đủ thông tin chọn nút ""Lưu"" hoặc ""Hủy""
 TH1: Chọn ""Lưu"" sẽ xảy ra ràng buộc thông báo những field bắt buộc nhập nếu bỏ sót 
-> Nếu ""Lưu"" thành công -> Quay lại màn hình danh sách nhân viên -> dữ liệu các thông tin nhân viên(MaNV, HoVaTen, GioiTinh, Sđt) sẽ thay đổi -> dữ liệu trong database thay đổi theo
TH2: Chọn ""Hủy"" tất cả dữ liệu mình điền trên các input sẽ clear đi -> Quay lại màn hình danh sách nhân viên -> dữ liệu trong database không thay đổi"

**Comment by hunglp2k1** [comment]
đã nhận
