### ISSUE TITLE
Xem chi tiết hóa đơn

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#56]
"- Nhân viên khi thanh toán hóa đơn -> Chi tiết hóa đơn được lưu trên database
- Có màn hình list tất cả các hóa đơn được lấy từ database -> Chọn 1 hóa đơn bất kì -> Hiển thị thông tin chi tiết của hóa đơn
- Thông tin gồm:
+ Mã hóa đơn
+ Các món ăn 
+ Số lượng từng món ăn
+ Tổng số tiền

**Comment by datnv72** [comment]
Đã nhận
