### ISSUE TITLE
Xem thống kê doanh thu

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#57]
-Giao diện
Hiện table bao gồm các coloumn: hóa đơn, Nhân viên, tên món ăn, giá , số lượng, tổng hóa đơn bên dưới sẽ có tổng doanh thu của các hóa đơn bán hàng
Input sắp xếp doanh thu theo ngày 
Button xuất báo cáo  thống kê doanh thu
Xử lí:
Khi quản trị viên Login (sprint 1) thành công, chọn vào chức năng thống kê doanh thu ->xử lý thống kê doanh thu, lấy dữ liệu từ database xử lý để cho hiển thị các thông tin cần hiển thị ra ở dạng bảng và tổng doanh thu bán hàng sẽ được thay đổi khi có hóa đơn mới. 
Dữ liệu: 
Dữ liệu được lưu trữ trong database

**Comment by thanhtai1812** [comment]
Đã nhận

**Comment by thanhtai1812** [comment]
Đã nhận
