### ISSUE TITLE
Thêm tài khoản nhân viên

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#58]
Giao diện:
Input của thêm tên tài khoản, mật khẩu, tên quyền
Button "Lưu" tài khoản
Button "Trở lại" về trang danh sách tài khoản
Xử Lý:
Trường Hợp 1: Khi không nhập vào trường input và ấn "Lưu" sẽ thông báo: Vui lòng điền đầy đủ thông tin 
Trường hợp 2: Sau khi điền đầy đủ thông tin > ấn button "Lưu" thì sẽ lưu thông tin đó vào danh sách tài khoản
Chọn button "trở lại" sẽ trở lại trang danh sách tài khoản
Lưu trữ:
tên tài khoản, mật khẩu, tên quyền sẽ được lưu vào database

**Comment by hunglp2k1** [comment]
đã nhận
