### ISSUE TITLE
Sửa tài khoản nhân viên

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#59]
Giao diện:
Input "Tên tài khoản","Mật khẩu", "tên quyền"
Button "Lưu"
Button "Trở lại"
Xử lý:
Trường hợp 1: khi để trống thông tin cần sửa, chọn button "Lưu" sẽ hiển thị thông báo "Vui lòng nhập đầy đủ thông tin"
Trường hợp 2: Sau khi sửa thông tin cần sửa chọn nút "Lưu" sẽ lưu lại thông tin đã sửa
Khi ấn button "Trở lại" sẽ trở về trang danh sách tài khoản
Lưu trữ:
Lưu trữ thông tin đã sửa vào database

**Comment by hunglp2k1** [comment]
đã nhận
