### ISSUE TITLE
Xóa tài khoản nhân viên

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#60]
Giao diện
Hiển thị thông tin của tên tài khoản , mật khẩu , quyền
Button "Xóa"
Button "Trở lại"
Xử lý:
Chọn button "Xóa", loại món ăn đó sẽ được xóa
Chọn "trở lại" để trở lại màn hình danh sáchtài khoản
Lưu trữ:
Những thông tin đã xóa thì sẽ bị xóa khỏi database

**Comment by Anllv** [comment]
đã nhận
