### ISSUE TITLE
Xem quyền truy cập tài khoản

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#62]
-Giao diện
Hiện table bao gồm các coloumn: Tên quyền, ghi chú
Các button: Thêm mới, Sửa, Xoá 
-Dữ liệu: Lưu các field , dữ liệu trong database
Xử lí:
Khi quản trị viên Login (sprint 1) thành công, chọn vào quyền -> Nếu có dữ liệu của quyền ở database thì sẽ render dữ liệu các cột theo dạng bảng.

**Comment by thanhtai1812** [comment]
Đã nhận
