### ISSUE TITLE
Tìm kiếm loại món ăn

### ISSUE THREAD

**Issue by thanhtai1812** [hunglp2k1/fast_food_app#64]
**Giao diện:**
+ Thanh tìm kiếm "Loại món ăn"
+ icon button "tìm kiếm"
**Xử lý:**
+ Trường hợp 1: Nhập thông tin tìm kiếm chọn icon button "tìm kiếm" sẽ hiển thị các loại món ăn có liên quan
+Trường hợp 2: Nhập thông tin tìm kiếm chọn icon button tìm kiếm" sẽ thông báo không có loại món ăn

**Comment by Anllv** [comment]
đã nhận
