### ISSUE TITLE
Danh sách loại món ăn

### ISSUE THREAD

**Issue by thanhtai1812** [hunglp2k1/fast_food_app#70]
-Giao diện
Hiện table bao gồm các coloumn: Tên loại món ăn
Các button: Thêm mới, Sửa, Xoá, Chi tiết.
Input tìm kiếm theo tên loại món ăn,
-Dữ liệu: Lưu các field , Loại món ăn,

Xử lí:
Khi quản trị viên Login (sprint 1) thành công, chọn vào danh mục thực đơn -> Chọn loại món ăn -> Nếu có dữ liệu của món ăn ở database thì sẽ render dữ liệu các cột theo dạng bảng.

**Comment by datnv72** [comment]
đã nhận
