### ISSUE TITLE
Danh sách món ăn

### ISSUE THREAD

**Issue by thanhtai1812** [hunglp2k1/fast_food_app#71]
-Giao diện
Hiện table bao gồm các coloumn: Tên món ăn, Loại Món Ăn, Mô tả, Hình ảnh,Giá, Số lượng
Các button: Thêm mới, Sửa, Xoá, Chi tiết.
Input tìm kiếm theo tên sản phẩm, Dropdownlist theo tên loại món ăn để tìm kiếm món ăn theo loại món ăn,
-Dữ liệu: Lưu các field Tên món ăn, Loại món ăn, mô tả, hình ảnh, giá, số lượng

Xử lí:
Khi quản trị viên Login (sprint 1) thành công, chọn vào danh mục thực đơn -> Chọn món ăn -> Nếu có dữ liệu của món ăn ở database thì sẽ render dữ liệu các cột theo dạng bảng.

**Comment by hunglp2k1** [comment]
đã nhận
