### ISSUE TITLE
Áp dụng khuyến mãi theo hóa đơn

### ISSUE THREAD

**Issue by hunglp2k1** [hunglp2k1/fast_food_app#72]
*Giao diện 
- Dropdownlist menu hiển thị danh sách khuyến mãi, button áp dụng khuyến mãi
*Xử lý :
- Đăng nhập thành công
- Session username đã được tạo
- Vào trang chủ
- Đã tạo giỏ hàng
- Session cart được tạo
- Chọn item khuyến mãi từ dropdownlist menu
- Nhấn button áp dụng khuyến mãi
- Tổng tiền giảm giá theo tỷ lệ phần trăm khuyến mãi(Áp dụng khuyến mãi cho đơn hàng > 200,000đ)
*Dữ liệu:
- Món ăn
- Số lượng món ăn
- Tỷ lệ giảm giá
- Thành tiền

**Comment by datnv72** [comment]
đã nhận
