### ISSUE TITLE
Xem danh sách tài khoản nhân viên

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#74]
-Giao diện
Hiện table bao gồm các coloumn: mã tài khoản, tên tài khoản, mật khẩu, quyền truy cập
Các button: Thêm mới, Sửa, Xoá,
Input tìm kiếm tên tài khoản
-Dữ liệu: Lưu các field mã tài khoản, tên tài khoản, mật khẩu, quyền truy cập
Xử lí:
Khi quản trị viên Login (sprint 1) thành công, chọn vào mục tài khoản -> Chọn tài khoản -> Nếu có dữ liệu của tài khoản ở database thì sẽ render dữ liệu các cột theo dạng bảng.

**Comment by hunglp2k1** [comment]
đã nhận
