### ISSUE TITLE
Xem danh sách khuyến mãi

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#75]
-Giao diện
Hiện table bao gồm các coloumn: tên khuyến mãi, mô tả, tỉ lệ khuyến mãi, ngày bắt đầu, này kết thúc
Các button: Thêm mới, Sửa, Xoá,
Input tìm kiếm khuyến mãi
-Dữ liệu: Lưu các field tên khuyến mãi, mô tả, tỉ lệ khuyến mãi, ngày bắt đầu, này kết thúc
Xử lí:
Khi quản trị viên Login (sprint 1) thành công, chọn vào mục khuyến mãi -> Chọn khuyến mãi -> Nếu có dữ liệu của khuyến mãi ở database thì sẽ render dữ liệu các cột theo dạng bảng.

**Comment by Anllv** [comment]
đã nhận
