### ISSUE TITLE
Thêm khuyến mãi

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#76]
giao diện:
Input của thêm khuyến mãi, input mô tả, input tỉ lệ giảm giá, input ngày bắt đầu, input, ngày kết thúc
Button "Lưu" khuyến mãi
Button "Trở lại" về trang danh sách khuyến mãi
Xử Lý:
Trường Hợp 1: Khi không nhập vào trường input tên khuyến mãi, input tỉ lệ khuyến mãi, input ngày bắt đầu, input, ngày kết thúc và ấn "Lưu" sẽ thông báo: Vui lòng điền đầy đủ thông tin khuyến mãi
Trường hợp 2: Sau khi điền đầy đủ thông tin > ấn button "Lưu" thì sẽ lưu thông tin đó vào danh sách khuyến mãi
Chọn button "trở lại" sẽ trở lại trang danh sách khuyến mãi
Lưu trữ:
MaKM, TenKM, Mota, Tilegiamgia, ngaybatdau, ngayketthuc sẽ được lưu vào database

**Comment by Anllv** [comment]
đã nhận
