### ISSUE TITLE
Sửa khuyến mãi 

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#77]
Giao diện:
Input "Tên khuyến mãi","mô tả","tỉ lệ giảm giá", "ngày bắt đầu", "Ngày kết thúc"
Button "Lưu"
Button "Trở lại"
Xử lý:
Trường hợp 1: khi để trống thông tin cần sửa, chọn button "Lưu" sẽ hiển thị thông báo "Vui lòng nhập đầy đủ thông tin"
Trường hợp 2: Sau khi sửa thông tin cần sửa chọn nút "Lưu" sẽ lưu lại thông tin đã sửa
Khi ấn button "Trở lại" sẽ trở về trang danh sách loại món ăn
Lưu trữ:
Lưu trữ thông tin Tên khuyến mãi","mô tả","tỉ lệ giảm giá", "ngày bắt đầu", "Ngày kết thúc" đã sửa vào database

**Comment by Anllv** [comment]
đã nhận
