### ISSUE TITLE
Xóa khuyến mãi

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#78]
Giao diện:
Hiển thị thông tin của tên khuyến mãi, mô tả, tỉ lệ khuyến mãi, ngày bắt đầu, ngày kết thúc
Button "Xóa"
Button "Trở lại"
Xử lý:
Chọn button "Xóa", khuyến mãi đó sẽ được xóa
Chọn "trở lại" để trở lại màn hình danh sách loại món ăn
Lưu trữ:
Những thông tin đã xóa thì sẽ bị xóa khỏi database

**Comment by Anllv** [comment]
đã nhận
