### ISSUE TITLE
Tìm kiếm khuyến mãi

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#79]
Giao diện:
Thanh tìm kiếm "khuyến mãi"
icon button "tìm kiếm"
Xử lý:
+Trường hợp 1: Nhập thông tin tìm kiếm chọn icon button "tìm kiếm" sẽ hiển thị các loại món ăn có liên quan
+Trường hợp 2: Nhập thông tin tìm kiếm chọn icon button tìm kiếm" sẽ thông báo không có loại món ăn

**Comment by thanhtai1812** [comment]
đã nhận
