### ISSUE TITLE
Tìm kiếm món ăn 

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#80]
*Giao diện :
Input tìm kiếm món ăn ,  Icon button search
*Xử lý:
-Đăng nhập thành công
- Session được tạo 
- Vào trang chủ
- Nhập các kí tự cần tìm  ->chọn Icon button search -> hệ thống sẽ tìm kiếm dưới database. Nếu kí tự thuộc tên món ăn thì sẽ hiển thị các món ăn có chứa kí tự đó (vd: nhập "ha"->hiển thị ra "hamburger 1","hamburger 2","hamburger 3"). Nếu kí tự không thuộc tên món ăn thì sẽ thông báo "không tìm thấy món ăn"
-  Nếu nhập chính xác tên món ăn -> chọn Icon button search -> hệ thống sẽ tìm kiếm dưới database. Nếu string thuộc tên món ăn thì sẽ hiển thị các món ăn có chứa string đó (vd: nhập "hamburger1"->hiển thị ra "hamburger 1","hamburger 2","hamburger 3"). Nếu string không thuộc tên món ăn thì sẽ thông báo "không tìm thấy món ăn"
*Dữ liệu:
- Tên món ăn

**Comment by thanhtai1812** [comment]
đã nhận
