### ISSUE TITLE
Xem danh sách đơn hàng

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#83]
Giao diện:
hiển thị thông tin gồm: Hóa đơn, nhân viên, ngày giờ thanh toán
input tìm kiếm hóa đơn và 1 icon search
input sắp xếp hóa đơn và 1 icon sắp xếp
Xử lý : 
Hiển thị tất cả các hóa đơn mà nhân viên khi đã thanh toán ở dạng list danh sách
Dữ liệu:
Nhân viên khi thanh toán hóa đơn ->  hóa đơn được lưu trên database

**Comment by datnv72** [comment]
đã nhận
