### ISSUE TITLE
Tìm kiếm hóa đơn

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#84]
Giao diện:
Input tìm kiếm hóa đơn và button icon tìm kiếm nằm trong màn hình danh sách hóa đơn
Xử lý :
để hiển thị thông tin cần tìm : 
Cần nhập các kí tự tìm kiếm hóa đơn -> nhấn nút button icon sẽ hiển thị ra các hóa đơn mà có các kí tự tìm kiếm
Cần nhập đúng tên hóa đơn tìm kiếm -> nhấn nút button icon sẽ hiển thị ra chính xác hóa đơn cần tìm kiếm 
Dữ liệu:
dữ liệu được lấy và lưu trữ trong database

**Comment by hunglp2k1** [comment]
đã nhận
