### ISSUE TITLE
Sắp xếp hóa đơn

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#85]
Giao diện:
input sắp xếp hóa đơn và button icon(datetime) nằm trong màn hình danh sách hóa đơn
Xử lý :
khi nhấn nút button icon -> sẽ hiển thị thông tin bảng (ngày tháng năm)-> chọn trong bảng datetime: từ (ngày) đến (ngày) sau đó hệ thống lấy dữ liệu từ database sẽ hiển thị ra các hóa đơn nằm trong khoảng (ngày ) bao nhiêu đó
Dữ liêu:
Dữ liệu lấy từ database

**Comment by hunglp2k1** [comment]
đã nhận
