### ISSUE TITLE
Xem danh sách nhân viên

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#86]
-Giao diện
Hiện table bao gồm các coloumn: Họ tên nhân viên, SĐT, ngày sinh, giới tính, chức vụ
Các button: Thêm mới, Sửa, Xoá.
Xử lí:
Khi quản trị viên Login (sprint 1) thành công,  Chọn nhân viên -> Nếu có dữ liệu của nhân viên ở database thì sẽ render dữ liệu các cột theo dạng bảng.
-Dữ liệu: Họ tên nhân viên, SĐT, ngày sinh, giới tính, chức vụ, mã nhân viên,

**Comment by datnv72** [comment]
đã nhận
