### ISSUE TITLE
Xem danh sách chức vụ

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#87]
-Giao diện
Hiện table bao gồm các coloumn: Tên chức vụ
Các button: Thêm mới, Sửa, Xoá,
Xử lí:
Khi quản trị viên Login (sprint 1) thành công, Chọn chức vụ -> Nếu có dữ liệu của chức vụ ở database thì sẽ render dữ liệu các cột theo dạng bảng.
-Dữ liệu: Lưu các field , mã chức vụ và tên chức vụ vào database,

**Comment by datnv72** [comment]
đã nhận
