### ISSUE TITLE
Thêm chức vụ

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#88]
Giao diện:
Input của thêm chức vụ
Button "Lưu" chức vụ
Button "Trở lại" về trang danh sách chức vụ
Xử Lý:
Trường Hợp 1: Khi không nhập vào trường input tên chức vụ và ấn "Lưu" sẽ thông báo: Vui lòng điền đầy đủ thông tin chức vụ
Trường hợp 2: Sau khi điền đầy đủ thông tin > ấn button "Lưu" thì sẽ lưu thông tin đó vào danh sách chức vụ
Chọn button "trở lại" sẽ trở lại trang danh sách chức vụ
Lưu trữ:
MaCV, Tên chức vụ  sẽ được lưu vào database

**Comment by datnv72** [comment]
đã nhận
