### ISSUE TITLE
Xóa chức vụ

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#90]
Giao diện
Hiển thị thông tin của tên chức vụ cần xóa
Button "Xóa"
Button "Trở lại"
Xử lý:
Chọn button "Xóa", chức vụ đó sẽ được xóa
Chọn "trở lại" để trở lại màn hình danh sách chức vụ
Lưu trữ:
Những thông tin đã xóa thì sẽ bị xóa khỏi database

**Comment by thanhtai1812** [comment]
đã nhận
