### ISSUE TITLE
Xóa quyền

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#91]
Hiển thị thông tin của tên quyền, ghi chú
Button "Xóa"
Button "Trở lại"
Xử lý:
Chọn button "Xóa", quyền đó sẽ được xóa
Chọn "trở lại" để trở lại màn hình danh sách quyền
Lưu trữ:
Những thông tin đã xóa thì sẽ bị xóa khỏi database

**Comment by thanhtai1812** [comment]
đã nhận
