### ISSUE TITLE
Thêm quyền

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#92]
Giao diện
Input "tên quyền" và input "Ghi chú"
Button "Lưu" quyền
Button "Trở lại" về trang danh sách quyền
Xử Lý:
Trường Hợp 1: Khi không nhập vào trường input (tên quyền, ghi chú)  và ấn "Lưu" sẽ thông báo: Vui lòng điền đầy đủ thông tin quyền 
Trường hợp 2: Sau khi điền đầy đủ thông tin > ấn button "Lưu" thì sẽ lưu thông tin đó vào danh sách quyền
Chọn button "trở lại" sẽ trở lại trang danh sách quyền
Lưu trữ:
MaQuyen, TenQuyen, GhiChu sẽ được lưu vào database

**Comment by hunglp2k1** [comment]
đã nhận
