### ISSUE TITLE
Sửa quyền

### ISSUE THREAD

**Issue by Anllv** [hunglp2k1/fast_food_app#93]
Giao diện:
Input "Tên quyền", và Input "Ghi chú"
Button "Lưu"
Button "Trở lại"
Xử lý:
Trường hợp 1: khi để trống thông tin cần sửa, chọn button "Lưu" sẽ hiển thị thông báo "Vui lòng nhập đầy đủ thông tin"
Trường hợp 2: Sau khi sửa thông tin cần sửa chọn nút "Lưu" sẽ lưu lại thông tin đã sửa
Khi ấn button "Trở lại" sẽ trở về trang danh sách quyền 
Lưu trữ:
Lưu trữ thông tin tên quyền và ghi chú đã sửa vào database

**Comment by hunglp2k1** [comment]
đã nhận
