### ISSUE TITLE
Sắp xếp món ăn

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#94]
*Giao diện:
- Dropdownlist-menu gồm 3 giá trị : mặc định, giá tăng dần, giá giảm dần
- Button sắp xếp 
*Xử lý
-Đăng nhập thành công
-Session được tạo
-Vào trang chủ
- Khi chọn giá trị mặc định ->nhấn chọn sắp xếp hệ thống sẽ không sắp xếp món ăn theo giá
- Khi chọn giá tăng dần -> nhấn chọn sắp xếp hệ thống sẽ lấy dữ liệu theo giá món ăn tăng dần
-  Khi chọn giá giảm dần -> nhấn chọn sắp xếp hệ thống sẽ lấy dữ liệu theo giá món ăn giảm dần
*Dữ liệu : Giá món ăn

**Comment by hunglp2k1** [comment]
Đã xong!
