### ISSUE TITLE
Xem thông tin cá nhân

### ISSUE THREAD

**Issue by datnv72** [hunglp2k1/fast_food_app#95]
*Giao diện 
- Hiển thị các thông tin theo dạng table  gồm: hình ảnh, tên nhân viên, giới tính và chức vụ
*Xử lý
- Đăng nhập thành công 
- Session đã tạo
- vào trang chủ
- Khi click vào navigation thông tin cá nhân -> hiển thị trang thông tin cá nhân gồm hình ảnh, tên nhân viên, giới tính và chức vụ

**Comment by Anllv** [comment]
đã nhận
